site_name: Software Engineering Best Practices, a Machine Learners Perspective
nav:
    - Home: index.md
    - Getting Started: getting_started.md
    - Dependencies: managing_depedencies.md
    - Linting and Formatting: linting_and_formatting.md

theme:
    name: material

markdown_extensions:
    - admonition
    - pymdownx.tabbed
    - pymdownx.superfences
    - pymdownx.highlight:
        use_pygments: true